# Saki API Schema (OpenAPI 3.0)

openapi: 3.0.0
info:
  title: Saki Property Listings API
  version: 1.0.0
  description: API schema for admin and property listing endpoints
servers:
  - url: /api
paths:
  /admin/property:
    get:
      summary: Get property by slug
      parameters:
        - in: query
          name: slug
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Property data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PropertyResponse'
    post:
      summary: Create or update a property
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PropertyPayload'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  error:
                    type: string
  /admin/media:
    get:
      summary: Get property media by slug
      parameters:
        - in: query
          name: slug
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Media data
          content:
            application/json:
              schema:
                type: object
    post:
      summary: Update property media
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Success
  /admin/upload:
    post:
      summary: Upload a file to a property folder
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                slug:
                  type: string
                folder:
                  type: string
                  enum: [hero, photos, floorplans, backgrounds, contactvideo, docs]
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Upload result
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  objectPath:
                    type: string
                  error:
                    type: string
  /admin/me:
    get:
      summary: Get current admin user info
      responses:
        '200':
          description: User info
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  allowed:
                    type: boolean
                  email:
                    type: string
                  uid:
                    type: string
                  name:
                    type: string
                  picture:
                    type: string
components:
  schemas:
    PropertyPayload:
      type: object
      properties:
        slug:
          type: string
        property:
          $ref: '#/components/schemas/Property'
    PropertyResponse:
      type: object
      properties:
        ok:
          type: boolean
        property:
          $ref: '#/components/schemas/Property'
        error:
          type: string
    Property:
      type: object
      properties:
        slug:
          type: string
        address:
          $ref: '#/components/schemas/PropertyAddress'
        price:
          $ref: '#/components/schemas/Money'
        beds:
          type: integer
        baths:
          type: integer
        homeSqft:
          type: integer
        lot:
          $ref: '#/components/schemas/Lot'
        headline:
          type: string
        description:
          type: string
        features:
          type: array
          items:
            type: string
        agent:
          $ref: '#/components/schemas/PropertyAgent'
        openHouses:
          type: array
          items:
            $ref: '#/components/schemas/OpenHouse'
        location:
          $ref: '#/components/schemas/PropertyLocation'
        media:
          $ref: '#/components/schemas/PropertyMedia'
    PropertyAddress:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        state:
          type: string
        zip:
          type: string
    Money:
      type: object
      properties:
        amount:
          type: number
        currency:
          type: string
          enum: [USD]
    Lot:
      type: object
      properties:
        acres:
          type: number
        sqft:
          type: number
    PropertyAgent:
      type: object
      properties:
        name:
          type: string
        phone:
          type: string
        email:
          type: string
        brokerage:
          type: string
        photoUrl:
          type: string
    OpenHouse:
      type: object
      properties:
        startIso:
          type: string
          format: date-time
        endIso:
          type: string
          format: date-time
        note:
          type: string
    PropertyLocation:
      type: object
      properties:
        lat:
          type: number
        lon:
          type: number
    PropertyMedia:
      type: object
      properties:
        hero:
          type: array
          items:
            type: string
        photos:
          type: array
          items:
            type: string
        photoSpaces:
          type: object
          additionalProperties:
            type: string
        photoSpaceOrder:
          type: array
          items:
            type: string
        floorplans:
          type: array
          items:
            type: string
        backgrounds:
          type: array
          items:
            type: string
        overviewBackdrop:
          type: string
        contactVideos:
          type: array
          items:
            type: string
        contactVideo:
          type: string
        documents:
          type: array
          items:
            type: object
            properties:
              label:
                type: string
              href:
                type: string
        video:
          type: object
          properties:
            title:
              type: string
            embedUrl:
              type: string
            mp4Url:
              type: string
            posterUrl:
              type: string
        tours:
          type: array
          items:
            type: object
            properties:
              label:
                type: string
              href:
                type: string
